namespace YoutubeStudio.Api.Services.Providers;

public sealed class PlaceholderResearchProvider : IResearchProvider
{
    public Task<ResearchResult> ResearchAsync(ResearchRequest request, CancellationToken cancellationToken)
    {
        return Task.FromResult(new ResearchResult(
            $"Initial research placeholder for: {request.Prompt.Trim()}",
            Array.Empty<string>()));
    }
}

public sealed class PlaceholderScriptProvider : IScriptProvider
{
    public Task<ScriptResult> GenerateScriptAsync(ScriptRequest request, CancellationToken cancellationToken)
    {
        var title = request.Prompt.Trim().Length <= 120 ? request.Prompt.Trim() : request.Prompt.Trim()[..120].TrimEnd() + "…";
        var script = $"HOOK: {request.Prompt.Trim()}\n\nBODY: This script is generated by the development provider.\n\nRESEARCH: {request.ResearchSummary}\n\nCTA: Subscribe for the next video.";
        return Task.FromResult(new ScriptResult(title, script));
    }
}

public sealed class PlaceholderScenePlanProvider : IScenePlanProvider
{
    public Task<ScenePlanResult> CreateScenePlanAsync(ScenePlanRequest request, CancellationToken cancellationToken)
    {
        return Task.FromResult(new ScenePlanResult([
            new ScenePlanItem(1, request.Script, "Opening hook / primary visual", 8),
            new ScenePlanItem(2, "Continue the main explanation.", "Supporting visual with readable on-screen context", 12),
            new ScenePlanItem(3, "Close with the key takeaway and CTA.", "Clean closing shot", 8)
        ]));
    }
}

public sealed class PlaceholderVoiceProvider : IVoiceProvider
{
    public Task<VoiceResult> GenerateVoiceAsync(VoiceRequest request, CancellationToken cancellationToken) =>
        Task.FromResult(new VoiceResult("placeholder-voice", TimeSpan.FromSeconds(Math.Max(1, request.Script.Length / 15))));
}

public sealed class PlaceholderVisualProvider : IVisualProvider
{
    public Task<VisualResult> GenerateVisualAsync(VisualRequest request, CancellationToken cancellationToken) =>
        Task.FromResult(new VisualResult("placeholder-visual", "placeholder"));
}

public sealed class PlaceholderMusicSfxProvider : IMusicSfxProvider
{
    public Task<MusicSfxResult> GenerateMusicSfxAsync(MusicSfxRequest request, CancellationToken cancellationToken) =>
        Task.FromResult(new MusicSfxResult("placeholder-music-sfx", "placeholder-audio"));
}

public sealed class PlaceholderCaptionProvider : ICaptionProvider
{
    public Task<CaptionResult> GenerateCaptionsAsync(CaptionRequest request, CancellationToken cancellationToken) =>
        Task.FromResult(new CaptionResult("placeholder-captions"));
}

public sealed class PlaceholderRenderProvider : IRenderProvider
{
    public Task<RenderResult> RenderAsync(RenderRequest request, CancellationToken cancellationToken) =>
        Task.FromResult(new RenderResult("placeholder-render", TimeSpan.FromSeconds(28)));
}

public sealed class PlaceholderQaProvider : IQaProvider
{
    public Task<QaResult> EvaluateAsync(QaRequest request, CancellationToken cancellationToken) =>
        Task.FromResult(new QaResult(true, Array.Empty<string>()));
}
