// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YoutubeStudio.Api.Data;

#nullable disable

namespace YoutubeStudio.Api.Migrations
{
    [DbContext(typeof(YoutubeStudioDbContext))]
    [Migration("20260929195120_AddAuditEvents")]
    partial class AddAuditEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YoutubeStudio.Api.Models.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailsJson")
                        .HasMaxLength(200000)
                        .HasColumnType("character varying(200000)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VideoProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VideoProjectId", "CreatedAtUtc");

                    b.HasIndex("WorkspaceId", "CreatedAtUtc");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("YoutubeStudio.Api.Models.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalChannelId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("pk_channels");

                    b.HasIndex("WorkspaceId", "Name")
                        .HasDatabaseName("ix_channels_workspace_id_name");

                    b.ToTable("channels", (string)null);
                });

            modelBuilder.Entity("YoutubeStudio.Api.Models.ContentGenome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttributesJson")
                        .IsRequired()
                        .HasMaxLength(200000)
                        .HasColumnType("character varying(200000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("SceneCount")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VideoProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("WordCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VideoProjectId")
                        .IsUnique();

                    b.ToTable("content_genomes", (string)null);
                });

            modelBuilder.Entity("YoutubeStudio.Api.Models.Opportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudienceProblem")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("OpportunityScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Rationale")
                        .HasColumnType("text");

                    b.Property<decimal>("RevenueScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("pk_opportunities");

                    b.HasIndex("WorkspaceId", "Status")
                        .HasDatabaseName("ix_opportunities_workspace_id_status");

                    b.ToTable("opportunities", (string)null);
                });

            modelBuilder.Entity("YoutubeStudio.Api.Models.ProductionArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasMaxLength(200000)
                        .HasColumnType("character varying(200000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(200000)
                        .HasColumnType("character varying(200000)");

                    b.Property<string>("ProviderAssetId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VideoProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VideoProjectId", "Type");

                    b.ToTable("production_artifacts", (string)null);
                });

            modelBuilder.Entity("YoutubeStudio.Api.Models.ProductionCost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("TotalCostUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("UnitCostUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("Units")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VideoProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VideoProjectId", "Stage");

                    b.ToTable("production_costs", (string)null);
                });

            modelBuilder.Entity("YoutubeStudio.Api.Models.ProductionJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("LastCompletedStage")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VideoProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VideoProjectId", "CreatedAtUtc");

                    b.ToTable("production_jobs", (string)null);
                });

            modelBuilder.Entity("YoutubeStudio.Api.Models.ResearchBrief", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Markdown")
                        .IsRequired()
                        .HasMaxLength(200000)
                        .HasColumnType("character varying(200000)");

                    b.Property<int>("PendingClaimCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ResearchProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("pk_research_briefs");

                    b.HasIndex("ResearchProjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_research_briefs_project_id");

                    b.HasIndex("WorkspaceId", "ResearchProjectId")
                        .HasDatabaseName("ix_research_briefs_workspace_id_project_id");

                    b.ToTable("research_briefs", (string)null);
                });

            modelBuilder.Entity("YoutubeStudio.Api.Models.ResearchClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasMaxLength(200000)
                        .HasColumnType("character varying(200000)");

                    b.Property<Guid>("ResearchProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("pk_research_claims");

                    b.HasIndex("ResearchProjectId")
                        .HasDatabaseName("IX_research_claims_ResearchProjectId");

                    b.HasIndex("WorkspaceId", "ResearchProjectId")
                        .HasDatabaseName("ix_research_claims_workspace_id_project_id");

                    b.ToTable("research_claims", (string)null);
                });

            modelBuilder.Entity("YoutubeStudio.Api.Models.ResearchClaimEvidence", b =>
                {
                    b.Property<Guid>("ResearchClaimId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResearchEvidenceId")
                        .HasColumnType("uuid");

                    b.HasKey("ResearchClaimId", "ResearchEvidenceId")
                        .HasName("pk_research_claim_evidence");

                    b.HasIndex("ResearchEvidenceId")
                        .HasDatabaseName("ix_research_claim_evidence_evidence_id");

                    b.ToTable("research_claim_evidence", (string)null);
                });

            modelBuilder.Entity("YoutubeStudio.Api.Models.ResearchEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Context")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Locator")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasMaxLength(200000)
                        .HasColumnType("character varying(200000)");

                    b.Property<string>("Quote")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<Guid>("ResearchSourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("pk_research_evidence");

                    b.HasIndex("ResearchSourceId", "CreatedAtUtc")
                        .HasDatabaseName("ix_research_evidence_source_id_created_at");

                    b.HasIndex("WorkspaceId", "ResearchSourceId")
                        .HasDatabaseName("ix_research_evidence_workspace_id_source_id");

                    b.ToTable("research_evidence", (string)null);
                });

            modelBuilder.Entity("YoutubeStudio.Api.Models.ResearchProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("pk_research_projects");

                    b.HasIndex("OpportunityId")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "CreatedAtUtc")
                        .HasDatabaseName("ix_research_projects_workspace_id_created_at");

                    b.ToTable("research_projects", (string)null);
                });

            modelBuilder.Entity("YoutubeStudio.Api.Models.ResearchSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasMaxLength(200000)
                        .HasColumnType("character varying(200000)");

                    b.Property<Guid>("ResearchProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("pk_research_sources");

                    b.HasIndex("ResearchProjectId", "CreatedAtUtc")
                        .HasDatabaseName("ix_research_sources_project_id_created_at");

                    b.HasIndex("WorkspaceId", "ResearchProjectId")
                        .HasDatabaseName("ix_research_sources_workspace_id_project_id");

                    b.ToTable("research_sources", (string)null);
                });

            modelBuilder.Entity("YoutubeStudio.Api.Models.VideoOutcome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AverageViewDurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<long>("Comments")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EstimatedRevenueUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<long>("Likes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("MeasuredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VideoProjectId")
                        .HasColumnType("uuid");

                    b.Property<long>("Views")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("VideoProjectId", "MeasuredAtUtc");

                    b.ToTable("video_outcomes", (string)null);
                });

            modelBuilder.Entity("YoutubeStudio.Api.Models.VideoProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<string>("Script")
                        .HasMaxLength(100000)
                        .HasColumnType("character varying(100000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("WorkspaceId", "Status");

                    b.ToTable("video_projects", (string)null);
                });

            modelBuilder.Entity("YoutubeStudio.Api.Models.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("pk_workspaces");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_workspaces_name");

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("YoutubeStudio.Api.Models.Channel", b =>
                {
                    b.HasOne("YoutubeStudio.Api.Models.Workspace", "Workspace")
                        .WithMany("Channels")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("YoutubeStudio.Api.Models.ContentGenome", b =>
                {
                    b.HasOne("YoutubeStudio.Api.Models.VideoProject", "VideoProject")
                        .WithMany()
                        .HasForeignKey("VideoProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VideoProject");
                });

            modelBuilder.Entity("YoutubeStudio.Api.Models.Opportunity", b =>
                {
                    b.HasOne("YoutubeStudio.Api.Models.Workspace", "Workspace")
                        .WithMany("Opportunities")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("YoutubeStudio.Api.Models.ProductionArtifact", b =>
                {
                    b.HasOne("YoutubeStudio.Api.Models.VideoProject", "VideoProject")
                        .WithMany()
                        .HasForeignKey("VideoProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VideoProject");
                });

            modelBuilder.Entity("YoutubeStudio.Api.Models.ProductionCost", b =>
                {
                    b.HasOne("YoutubeStudio.Api.Models.VideoProject", "VideoProject")
                        .WithMany()
                        .HasForeignKey("VideoProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VideoProject");
                });

            modelBuilder.Entity("YoutubeStudio.Api.Models.ProductionJob", b =>
                {
                    b.HasOne("YoutubeStudio.Api.Models.VideoProject", "VideoProject")
                        .WithMany()
                        .HasForeignKey("VideoProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VideoProject");
                });

            modelBuilder.Entity("YoutubeStudio.Api.Models.ResearchBrief", b =>
                {
                    b.HasOne("YoutubeStudio.Api.Models.ResearchProject", "ResearchProject")
                        .WithOne("Brief")
                        .HasForeignKey("YoutubeStudio.Api.Models.ResearchBrief", "ResearchProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResearchProject");
                });

            modelBuilder.Entity("YoutubeStudio.Api.Models.ResearchClaim", b =>
                {
                    b.HasOne("YoutubeStudio.Api.Models.ResearchProject", "ResearchProject")
                        .WithMany()
                        .HasForeignKey("ResearchProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResearchProject");
                });

            modelBuilder.Entity("YoutubeStudio.Api.Models.ResearchClaimEvidence", b =>
                {
                    b.HasOne("YoutubeStudio.Api.Models.ResearchClaim", "ResearchClaim")
                        .WithMany("EvidenceLinks")
                        .HasForeignKey("ResearchClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YoutubeStudio.Api.Models.ResearchEvidence", "ResearchEvidence")
                        .WithMany("ClaimLinks")
                        .HasForeignKey("ResearchEvidenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResearchClaim");

                    b.Navigation("ResearchEvidence");
                });

            modelBuilder.Entity("YoutubeStudio.Api.Models.ResearchEvidence", b =>
                {
                    b.HasOne("YoutubeStudio.Api.Models.ResearchSource", "ResearchSource")
                        .WithMany("Evidence")
                        .HasForeignKey("ResearchSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResearchSource");
                });

            modelBuilder.Entity("YoutubeStudio.Api.Models.ResearchProject", b =>
                {
                    b.HasOne("YoutubeStudio.Api.Models.Opportunity", "Opportunity")
                        .WithMany()
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opportunity");
                });

            modelBuilder.Entity("YoutubeStudio.Api.Models.ResearchSource", b =>
                {
                    b.HasOne("YoutubeStudio.Api.Models.ResearchProject", "ResearchProject")
                        .WithMany("Sources")
                        .HasForeignKey("ResearchProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResearchProject");
                });

            modelBuilder.Entity("YoutubeStudio.Api.Models.VideoOutcome", b =>
                {
                    b.HasOne("YoutubeStudio.Api.Models.VideoProject", "VideoProject")
                        .WithMany()
                        .HasForeignKey("VideoProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VideoProject");
                });

            modelBuilder.Entity("YoutubeStudio.Api.Models.VideoProject", b =>
                {
                    b.HasOne("YoutubeStudio.Api.Models.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("YoutubeStudio.Api.Models.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("YoutubeStudio.Api.Models.ResearchClaim", b =>
                {
                    b.Navigation("EvidenceLinks");
                });

            modelBuilder.Entity("YoutubeStudio.Api.Models.ResearchEvidence", b =>
                {
                    b.Navigation("ClaimLinks");
                });

            modelBuilder.Entity("YoutubeStudio.Api.Models.ResearchProject", b =>
                {
                    b.Navigation("Brief");

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("YoutubeStudio.Api.Models.ResearchSource", b =>
                {
                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("YoutubeStudio.Api.Models.Workspace", b =>
                {
                    b.Navigation("Channels");

                    b.Navigation("Opportunities");
                });
#pragma warning restore 612, 618
        }
    }
}
